export interface ExamOption {
  id: string;
  label: string;
}

export const EXAM_LIST: ExamOption[] = [
  { id: 'NEET_UG', label: 'NEET (UG) — National Eligibility Entrance Test' },
  { id: 'NDA_NA', label: 'NDA & NA — National Defence Academy' },
  { id: 'UPSC_CSE', label: 'UPSC CSE — Civil Services Examination' },
  { id: 'SSC_CGL', label: 'SSC CGL — Combined Graduate Level' },
  { id: 'SSC_CHSL', label: 'SSC CHSL' },
  { id: 'SSC_MTS', label: 'SSC MTS' },
  { id: 'SSC_GD', label: 'SSC GD' },
  { id: 'UPSC_CAPF', label: 'UPSC CAPF' },
  { id: 'UPPSC_PCS', label: 'UPPSC PCS' },
  { id: 'WBCS', label: 'WBCS' },
  { id: 'BPSC_PCS', label: 'BPSC PCS' },
  { id: 'RRB_NTPC', label: 'RRB NTPC' },
  { id: 'RRB_JE', label: 'RRB JE' },
  { id: 'IBPS_PO', label: 'IBPS PO' },
  { id: 'SBI_PO', label: 'SBI PO' },
  { id: 'IBPS_CLERK', label: 'IBPS Clerk' },
  { id: 'CDS', label: 'CDS' },
  { id: 'CTET', label: 'CTET' },
  { id: 'UGC_NET', label: 'UGC NET' },
  { id: 'JENPAS_UG', label: 'JENPAS UG' },
  { id: 'JEPBN', label: 'JEPBN' },
  { id: 'ANM_GNM', label: 'ANM & GNM' },
  { id: 'SMFWBEE', label: 'SMFWBEE' },
  { id: 'WBPSC_FOOD_SI', label: 'WBPSC Food SI' },
  { id: 'JELET', label: 'JELET' },
  { id: 'JEXPO_VOCLET', label: 'JEXPO / VOCLET' },
  { id: 'UP_CNET', label: 'UP CNET' },
  { id: 'UP_GET', label: 'UPGET' },
  { id: 'JEECUP', label: 'JEECUP' },
  { id: 'UPSSSC_XRAY_TECHNICIAN', label: 'UPSSSC X-Ray Technician' },
  { id: 'UPSSSC_LAB_TECHNICIAN', label: 'UPSSSC Lab Technician' },
  { id: 'BIHAR_DCECE_PM', label: 'Bihar DCECE Paramedical' },
  { id: 'BIHAR_BCECE', label: 'Bihar BCECE' },
  { id: 'MP_PAT', label: 'MP PAT' },
  { id: 'MP_PNST', label: 'MP PNST' },
  { id: 'RUHS_BSC_NURSING', label: 'RUHS B.Sc Nursing' },
  { id: 'RAJASTHAN_JET', label: 'Rajasthan JET' },
  { id: 'UP_POLICE_CONSTABLE', label: 'UP Police Constable' },
  { id: 'UP_POLICE_SI', label: 'UP Police SI' },
  { id: 'BIHAR_POLICE_CONSTABLE', label: 'Bihar Police Constable' },
  { id: 'BIHAR_POLICE_SI', label: 'Bihar Police SI' },
  { id: 'WBP_CONSTABLE', label: 'WBP Constable' },
  { id: 'KP_CONSTABLE', label: 'KP Constable' },
  { id: 'MP_POLICE_CONSTABLE', label: 'MP Police Constable' },
  { id: 'RAJASTHAN_POLICE_CONSTABLE', label: 'Rajasthan Police Constable' },
  { id: 'IMU_CET', label: 'IMU CET (Merchant Navy)' },
  { id: 'ACET', label: 'ACET' },
  { id: 'ADMISSION_TESTS', label: 'Admission Tests' },
  { id: 'AIEEA_PG', label: 'AIEEA PG' },
  { id: 'AIEEA_UG', label: 'AIEEA UG' },
  { id: 'AIIMS_BSC', label: 'AIIMS B.Sc' },
  { id: 'AIIMS_MSC', label: 'AIIMS M.Sc' },
  { id: 'AIR_FORCE_COMMON_ADMISSIO', label: 'Air Force Common Admission Test' },
  { id: 'ALIGARH_MUSLIM_UNIVERSITY', label: 'Aligarh Muslim University Engineering Entrance Examination' },
  { id: 'ALL_INDIA_AYUSH_POST_GRAD', label: 'All India Ayush Post Graduate Entrance Test' },
  { id: 'ALL_INDIA_BAR_EXAMINATION', label: 'All India Bar Examination' },
  { id: 'ALL_INDIA_LAW_ENTRANCE_TE', label: 'All India Law Entrance Test' },
  { id: 'AMRITA_ENGINEERING_ENTRAN', label: 'Amrita Engineering Entrance Examination' },
  { id: 'ANDHRA_PRADESH_AGRICULTUR', label: 'Andhra Pradesh Agriculture Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_DIPLOMA_IN', label: 'Andhra Pradesh Diploma in Elementary Education Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_EDUCATION_', label: 'Andhra Pradesh Education Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_ENGINEERIN', label: 'Andhra Pradesh Engineering Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_INTEGRATED', label: 'Andhra Pradesh Integrated Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_LANGUAGE_P', label: 'Andhra Pradesh Language Pandit Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_LAW_COMMON', label: 'Andhra Pradesh Law Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_POLYTECHNI', label: 'Andhra Pradesh Polytechnic Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_POST_GRADU', label: 'Andhra Pradesh Post Graduate Common Entrance Test' },
  { id: 'ANDHRA_PRADESH_RESEARCH_C', label: 'Andhra Pradesh Research Common Entrance Test' },
  { id: 'ANNUAL_REFRESHER_PROGRAMM', label: 'Annual Refresher Programme In Teaching' },
  { id: 'APRDC_CET', label: 'APRDC CET' },
  { id: 'APRS_CAT', label: 'APRS CAT' },
  { id: 'ARUNACHAL_PRADESH_JOINT_E', label: 'Arunachal Pradesh Joint Entrance Examination' },
  { id: 'ASSAM_COMBINED_ENTRANCE_E', label: 'Assam Combined Entrance Examination' },
  { id: 'ASSAM_DELED_PET', label: 'Assam D.El.Ed PET' },
  { id: 'ASSAM_PAT', label: 'Assam PAT' },
  { id: 'BANARAS_HINDU_UNIVERSITY_', label: 'Banaras Hindu University Postgraduate Entrance Test' },
  { id: 'BHU_SET', label: 'BHU SET' },
  { id: 'BIHAR_BED', label: 'Bihar B.Ed' },
  { id: 'BIHAR_COMBINED_ENTRANCE_C', label: 'Bihar Combined Entrance Competitive Examination' },
  { id: 'BIHAR_DELED', label: 'Bihar D.El.Ed' },
  { id: 'BIHAR_INTEGRATED_BED', label: 'Bihar Integrated B.Ed' },
  { id: 'BIRLA_INSTITUTE_OF_TECHNO', label: 'Birla Institute of Technology and Science Admission Test' },
  { id: 'CDAC_CAT', label: 'CDAC CAT' },
  { id: 'CEE_KERALA_LLB_3_YEAR', label: 'CEE Kerala LLB 3 Year' },
  { id: 'CEE_KERALA_LLB_5_YEAR', label: 'CEE Kerala LLB 5 Year' },
  { id: 'CEE_KERALA_LLM', label: 'CEE Kerala LLM' },
  { id: 'CEETA_PG', label: 'CEETA PG' },
  { id: 'CG_BSC_NURSING', label: 'CG B.Sc Nursing' },
  { id: 'CG_MSC_NURSING', label: 'CG M.Sc Nursing' },
  { id: 'CG_PAT', label: 'CG PAT' },
  { id: 'CG_PET', label: 'CG PET' },
  { id: 'CG_POST_BASIC_NURSING', label: 'CG Post Basic Nursing' },
  { id: 'CG_PPHT', label: 'CG PPHT' },
  { id: 'CG_PPT', label: 'CG PPT' },
  { id: 'CG_PRE_BED', label: 'CG Pre B.Ed' },
  { id: 'CG_PRE_BA_BSC_BED', label: 'CG Pre BA B.Sc B.Ed' },
  { id: 'CG_PRE_DELED', label: 'CG Pre D.El.Ed' },
  { id: 'CG_PRE_MCA', label: 'CG Pre MCA' },
  { id: 'CHANDIGARH_BED_CET', label: 'Chandigarh B.Ed CET' },
  { id: 'CMI_ENTRANCE_EXAM', label: 'CMI Entrance Exam' },
  { id: 'COMEDK_UNDERGRADUATE_ENTR', label: 'COMEDK Undergraduate Entrance Test' },
  { id: 'COMMON_ADMISSION_TEST', label: 'Common Admission Test' },
  { id: 'COMMON_ENTRANCE_EXAMINATI', label: 'Common Entrance Examination for Design' },
  { id: 'COMMON_LAW_ADMISSION_TEST', label: 'Common Law Admission Test' },
  { id: 'COMMON_MANAGEMENT_ADMISSI', label: 'Common Management Admission Test' },
  { id: 'COMMON_UNIVERSITY_ENTRANC', label: 'Common University Entrance Test' },
  { id: 'CUSAT_COMMON_ADMISSION_TE', label: 'CUSAT Common Admission Test' },
  { id: 'DCECE', label: 'DCECE' },
  { id: 'DU_SOL', label: 'DU SOL' },
  { id: 'DUET', label: 'DUET' },
  { id: 'GATB_BET', label: 'GAT-B / BET' },
  { id: 'GLAT', label: 'GLAT' },
  { id: 'GRADUATE_APTITUDE_TEST_IN', label: 'Graduate Aptitude Test in Engineering' },
  { id: 'GRADUATE_PHARMACY_APTITUD', label: 'Graduate Pharmacy Aptitude Test' },
  { id: 'HARYANA_DELED', label: 'Haryana D.El.Ed' },
  { id: 'HIMACHAL_PRADESH_COMMON_E', label: 'Himachal Pradesh Common Entrance Test' },
  { id: 'HP_BED', label: 'HP B.Ed' },
  { id: 'HP_BSC_NURSING', label: 'HP B.Sc. Nursing' },
  { id: 'HP_DELED', label: 'HP D.El.Ed' },
  { id: 'HP_LEET', label: 'HP LEET' },
  { id: 'HP_MSC_NURSING', label: 'HP M.Sc Nursing' },
  { id: 'HP_PAT', label: 'HP PAT' },
  { id: 'HP_POST_BASIC_BSC_NURSING', label: 'HP Post Basic B.Sc Nursing' },
  { id: 'HSEE', label: 'HSEE' },
  { id: 'ICAR_JRF_SRF', label: 'ICAR JRF / SRF' },
  { id: 'ICMR_JRF', label: 'ICMR JRF' },
  { id: 'IFTK', label: 'IFTK' },
  { id: 'IGKV_CET', label: 'IGKV CET' },
  { id: 'IGNOU_BED', label: 'IGNOU B.Ed' },
  { id: 'IGNOU_OPENMAT', label: 'IGNOU OPENMAT' },
  { id: 'IGNOU_OPENNET', label: 'IGNOU OPENNET' },
  { id: 'IGNOU_PHD', label: 'IGNOU Ph.D' },
  { id: 'IIMC', label: 'IIMC' },
  { id: 'IISER_APTITUDE_TEST', label: 'IISER Aptitude Test' },
  { id: 'IITE', label: 'IITE' },
  { id: 'INDIAN_INSTITUTE_OF_FOREI', label: 'Indian Institute of Foreign Trade MBA Entrance Exam' },
  { id: 'INDIAN_MARITIME_UNIVERSIT', label: 'Indian Maritime University Common Entrance Test' },
  { id: 'INSTITUTE_OF_NATIONAL_IMP', label: 'Institute of National Importance Combined Entrance Test' },
  { id: 'INTEGRATED_PROGRAMME_IN_M', label: 'Integrated Programme in Management Aptitude Test' },
  { id: 'ITICAT', label: 'ITICAT' },
  { id: 'JAMMU_AND_KASHMIR_COMMON_', label: 'Jammu and Kashmir Common Entrance Test' },
  { id: 'JAWAHARLAL_NEHRU_UNIVERSI', label: 'Jawaharlal Nehru University Entrance Examination' },
  { id: 'JECA', label: 'JECA' },
  { id: 'JEEDEC', label: 'JEEDEC' },
  { id: 'JEMAS_PG', label: 'JEMAS PG' },
  { id: 'JEMSCN', label: 'JEMScN' },
  { id: 'JENPAUH_JENPAS_UG', label: 'JENPAUH / JENPAS (UG)' },
  { id: 'JEXPO', label: 'JEXPO' },
  { id: 'JHARKHAND_ANM_GNM', label: 'Jharkhand ANM GNM' },
  { id: 'JHARKHAND_BED', label: 'Jharkhand B.Ed' },
  { id: 'JHARKHAND_BSC_NURSING', label: 'Jharkhand B.Sc Nursing' },
  { id: 'JHARKHAND_COMBINED_ENTRAN', label: 'Jharkhand Combined Entrance Competitive Examination' },
  { id: 'JHARKHAND_DECE_LE', label: 'Jharkhand DECE LE' },
  { id: 'JHARKHAND_EECE_LE', label: 'Jharkhand EECE LE' },
  { id: 'JHARKHAND_PARAMEDICAL', label: 'Jharkhand Paramedical' },
  { id: 'JHARKHAND_POLYTECHNIC', label: 'Jharkhand Polytechnic' },
  { id: 'JHARKHAND_POST_BASIC_NURS', label: 'Jharkhand Post Basic Nursing' },
  { id: 'JK_BED', label: 'JK B.Ed' },
  { id: 'JK_DIPLOMA_POLYTECHNIC', label: 'JK Diploma Polytechnic' },
  { id: 'JKBOPEE_BSC_NURSING', label: 'JKBOPEE B.Sc Nursing' },
  { id: 'JOINT_ADMISSION_TEST_FOR_', label: 'Joint Admission Test for M.Sc' },
  { id: 'JOINT_ENTRANCE_EXAMINATIO', label: 'Joint Entrance Examination Advanced' },
  { id: 'JOINT_ENTRANCE_SCREENING_', label: 'Joint Entrance Screening Test' },
  { id: 'JOINT_INTEGRATED_PROGRAMM', label: 'Joint Integrated Programme in Management Admission Test' },
  { id: 'KARNATAKA_COMMON_ENTRANCE', label: 'Karnataka Common Entrance Test' },
  { id: 'KARNATAKA_DELED', label: 'Karnataka D.El.Ed' },
  { id: 'KARNATAKA_DIPLOMA_COMMON_', label: 'Karnataka Diploma Common Entrance Test' },
  { id: 'KARNATAKA_POST_GRADUATE_C', label: 'Karnataka Post Graduate Common Entrance Test' },
  { id: 'KERALA_ENGINEERING_ARCHIT', label: 'Kerala Engineering Architecture Medical' },
  { id: 'KERALA_PG_NURSING', label: 'Kerala PG Nursing' },
  { id: 'KMAT_KERALA', label: 'KMAT Kerala' },
  { id: 'LPUNEST', label: 'LPUNEST' },
  { id: 'MAHARASHTRA_BED', label: 'Maharashtra B.Ed' },
  { id: 'MAHARASHTRA_COMMON_ENTRAN', label: 'Maharashtra Common Entrance Test' },
  { id: 'MAHARASHTRA_LLB_COMMON_EN', label: 'Maharashtra LLB Common Entrance Test' },
  { id: 'MAHARASHTRA_MBA_MMS_COMMO', label: 'Maharashtra MBA / MMS Common Entrance Test' },
  { id: 'MAHARASHTRA_MCA_COMMON_EN', label: 'Maharashtra MCA Common Entrance Test' },
  { id: 'MP_ADDET_DAHET', label: 'MP ADDET (DAHET)' },
  { id: 'MP_CPCT', label: 'MP CPCT' },
  { id: 'MP_PPT', label: 'MP PPT' },
  { id: 'MP_PVFT', label: 'MP PVFT' },
  { id: 'NATIONAL_APTITUDE_TEST_IN', label: 'National Aptitude Test in Architecture' },
  { id: 'NATIONAL_ELIGIBILITY_CUM_', label: 'National Eligibility cum Entrance Test (MDS)' },
  { id: 'NATIONAL_ENTRANCE_SCREENI', label: 'National Entrance Screening Test' },
  { id: 'NATIONAL_INSTITUTE_OF_FAS', label: 'National Institute of Fashion Technology Entrance Examination' },
  { id: 'NCHMCT_JOINT_ENTRANCE_EXA', label: 'NCHMCT Joint Entrance Examination' },
  { id: 'NERIST_NEE', label: 'NERIST NEE' },
  { id: 'NID', label: 'NID' },
  { id: 'NIPER_JOINT_ENTRANCE_EXAM', label: 'NIPER Joint Entrance Examination' },
  { id: 'NIT_MCA_COMMON_ENTRANCE_T', label: 'NIT MCA Common Entrance Test' },
  { id: 'ODISHA_BED', label: 'Odisha B.Ed' },
  { id: 'ODISHA_CPET', label: 'Odisha CPET' },
  { id: 'ODISHA_JOINT_ENTRANCE_EXA', label: 'Odisha Joint Entrance Examination' },
  { id: 'OUAT', label: 'OUAT' },
  { id: 'PDPU', label: 'PDPU' },
  { id: 'PPMET', label: 'PPMET' },
  { id: 'PU_CET_PG', label: 'PU CET PG' },
  { id: 'PU_LAW_PG', label: 'PU LAW PG' },
  { id: 'PU_LAW_UG', label: 'PU LAW UG' },
  { id: 'PU_MBA_ENTRANCE_TEST', label: 'PU MBA Entrance Test' },
  { id: 'PU_MET', label: 'PU MET' },
  { id: 'PU_PHD', label: 'PU PhD' },
  { id: 'PUBDET', label: 'PUBDET' },
  { id: 'PUCET', label: 'PUCET' },
  { id: 'PULEET', label: 'PULEET' },
  { id: 'PUMDET', label: 'PUMDET' },
  { id: 'PUMEET', label: 'PUMEET' },
  { id: 'PUNJAB_BED', label: 'Punjab B.Ed' },
  { id: 'PUTHAT', label: 'PUTHAT' },
  { id: 'PWC_BCOM_ENTRANCE', label: 'PWC B.Com Entrance' },
  { id: 'PWC_BA_BSC_ENTRANCE', label: 'PWC BA B.Sc Entrance' },
  { id: 'RAJASTHAN_BSTC', label: 'Rajasthan BSTC' },
  { id: 'RAJASTHAN_PRE_PG', label: 'Rajasthan Pre PG' },
  { id: 'RAJASTHAN_PRE_TEACHER_EDU', label: 'Rajasthan Pre Teacher Education Test' },
  { id: 'RIE_CEE', label: 'RIE CEE' },
  { id: 'RUHS_BPT', label: 'RUHS BPT' },
  { id: 'RUHS_CUET', label: 'RUHS CUET' },
  { id: 'RUHS_MSC_NURSING', label: 'RUHS M.Sc Nursing' },
  { id: 'RUHS_PARAMEDICAL', label: 'RUHS Paramedical' },
  { id: 'RUHS_PHARMA', label: 'RUHS Pharma' },
  { id: 'RUHS_POST_BASIC_BSC_NURSI', label: 'RUHS Post Basic B.Sc Nursing' },
  { id: 'RULET', label: 'RULET' },
  { id: 'SEMESTER_EXAMS', label: 'Semester Exams' },
  { id: 'SWAYAM', label: 'SWAYAM' },
  { id: 'SYMBIOSIS_NATIONAL_APTITU', label: 'Symbiosis National Aptitude Test' },
  { id: 'TAMIL_NADU_COMMON_ENTRANC', label: 'Tamil Nadu Common Entrance Test' },
  { id: 'TELANGANA_COMMON_POST_GRA', label: 'Telangana Common Post Graduate Entrance Test' },
  { id: 'TELANGANA_DIPLOMA_IN_ELEM', label: 'Telangana Diploma in Elementary Education Common Entrance Test' },
  { id: 'TELANGANA_EDUCATION_COMMO', label: 'Telangana Education Common Entrance Test' },
  { id: 'TELANGANA_ENGINEERING_COM', label: 'Telangana Engineering Common Entrance Test' },
  { id: 'TELANGANA_ENGINEERING_AGR', label: 'Telangana Engineering, Agriculture and Pharmacy Common Entrance Test' },
  { id: 'TELANGANA_INTEGRATED_COMM', label: 'Telangana Integrated Common Entrance Test' },
  { id: 'TELANGANA_LAW_COMMON_ENTR', label: 'Telangana Law Common Entrance Test' },
  { id: 'TELANGANA_POLYTECHNIC_COM', label: 'Telangana Polytechnic Common Entrance Test' },
  { id: 'TELANGANA_POST_GRADUATE_E', label: 'Telangana Post Graduate Engineering Common Entrance Test' },
  { id: 'TELANGANA_POST_GRADUATE_L', label: 'Telangana Post Graduate Law Common Entrance Test' },
  { id: 'TIFR_GS', label: 'TIFR GS' },
  { id: 'TISSNET', label: 'TISSNET' },
  { id: 'TS_AGRICET', label: 'TS AGRICET' },
  { id: 'ULET', label: 'ULET' },
  { id: 'UNDERGRADUATE_COMMON_ENTR', label: 'Undergraduate Common Entrance Examination for Design' },
  { id: 'UP_BED', label: 'UP B.Ed' },
  { id: 'UPCATET', label: 'UPCATET' },
  { id: 'UTTARAKHAND_DELED', label: 'Uttarakhand D.El.Ed' },
  { id: 'VMOU_BED', label: 'VMOU B.Ed' },
  { id: 'WB_ANM_GNM', label: 'WB ANM GNM' },
  { id: 'WBJEE_JEHOM', label: 'WBJEE JEHOM' },
  { id: 'WEST_BENGAL_JOINT_ENTRANC', label: 'West Bengal Joint Entrance Examination' },
  { id: 'XAVIER_APTITUDE_TEST', label: 'Xavier Aptitude Test' },
  { id: 'ANDHRA_PRADESH_TEACHER_EL', label: 'Andhra Pradesh Teacher Eligibility Test' },
  { id: 'ASSAM_PUBLIC_SERVICE_COMM', label: 'Assam Public Service Commission' },
  { id: 'ASSAM_TEACHER_ELIGIBILITY', label: 'Assam Teacher Eligibility Test' },
  { id: 'CENTRAL_ARMED_POLICE_FORC', label: 'Central Armed Police Forces Assistant Commandant' },
  { id: 'CENTRAL_TEACHER_ELIGIBILI', label: 'Central Teacher Eligibility Test' },
  { id: 'CHHATTISGARH_PUBLIC_SERVI', label: 'Chhattisgarh Public Service Commission' },
  { id: 'CISF_AC_LDCE', label: 'CISF AC LDCE' },
  { id: 'COMBINED_DEFENCE_SERVICES', label: 'Combined Defence Services Examination' },
  { id: 'COMBINED_GEOSCIENTIST_EXA', label: 'Combined Geo-Scientist Examination' },
  { id: 'COMBINED_MEDICAL_SERVICES', label: 'Combined Medical Services Examination' },
  { id: 'CSIR_NATIONAL_ELIGIBILITY', label: 'CSIR National Eligibility Test' },
  { id: 'ENGINEERING_SERVICES_EXAM', label: 'Engineering Services Examination' },
  { id: 'GOA_TEACHER_ELIGIBILITY_T', label: 'Goa Teacher Eligibility Test' },
  { id: 'GOVT_JOBS_EXAMS', label: 'Govt Jobs Exams' },
  { id: 'GROUP_D', label: 'Group D' },
  { id: 'GUJARAT_TET', label: 'Gujarat TET' },
  { id: 'HARYANA_TEACHER_ELIGIBILI', label: 'Haryana Teacher Eligibility Test' },
  { id: 'IAS', label: 'IAS' },
  { id: 'INDIAN_ECONOMIC_SERVICE_I', label: 'Indian Economic Service / Indian Statistical Service Examination' },
  { id: 'INDIAN_FOREST_SERVICE_EXA', label: 'Indian Forest Service Examination' },
  { id: 'KARNATAKA_STATE_ELIGIBILI', label: 'Karnataka State Eligibility Test' },
  { id: 'MADHYA_PRADESH_TEACHER_EL', label: 'Madhya Pradesh Teacher Eligibility Test' },
  { id: 'MAHARASHTRA_STATE_ELIGIBI', label: 'Maharashtra State Eligibility Test' },
  { id: 'NATIONAL_DEFENCE_ACADEMY_', label: 'National Defence Academy and Naval Academy Examination' },
  { id: 'NHTET', label: 'NHTET' },
  { id: 'PUNJAB_STATE_TEACHER_ELIG', label: 'Punjab State Teacher Eligibility Test' },
  { id: 'RAILWAY_PROTECTION_FORCE_', label: 'Railway Protection Force Constable' },
  { id: 'RAJASTHAN_ELIGIBILITY_EXA', label: 'Rajasthan Eligibility Examination for Teachers' },
  { id: 'RAJASTHAN_PUBLIC_SERVICE_', label: 'Rajasthan Public Service Commission' },
  { id: 'STAFF_SELECTION_COMMISSIO', label: 'Staff Selection Commission Central Police Organisation' },
  { id: 'UGC_NATIONAL_ELIGIBILITY_', label: 'UGC National Eligibility Test' },
  { id: 'UPSC_SO_STENO_LDCE', label: 'UPSC SO Steno LDCE' },
  { id: 'UPSSSC_PET', label: 'UPSSSC PET' },
  { id: 'UTTAR_PRADESH_TEACHER_ELI', label: 'Uttar Pradesh Teacher Eligibility Test' },
  { id: 'PRAVESHIKA', label: 'Praveshika' },
  { id: 'VARISHTHA_UPADHYAY', label: 'Varishtha Upadhyay' },
  { id: 'ALL_INDIA_SAINIK_SCHOOL_E', label: 'All India Sainik School Entrance Examination' },
  { id: 'APRJC_CET', label: 'APRJC CET' },
  { id: 'INTERNATIONAL_JUNIOR_SCIE', label: 'International Junior Science Olympiad' },
  { id: 'JAWAHAR_NAVODAYA_VIDYALAY', label: 'Jawahar Navodaya Vidyalaya Selection Test' },
  { id: 'LEST', label: 'LEST' },
  { id: 'MSCE_PUP_PSS', label: 'MSCE PUP PSS' },
  { id: 'NATIONAL_INSTITUTE_OF_OPE', label: 'National Institute of Open Schooling Class 10' },
  { id: 'NATIONAL_TALENT_SEARCH_EX', label: 'National Talent Search Examination' },
  { id: 'RGNV', label: 'RGNV' },
  { id: 'RIMC', label: 'RIMC' },
  { id: 'STSE', label: 'STSE' },
  { id: 'TAPAS', label: 'TAPAS' },
  { id: 'TRUST', label: 'TRUST' }
];
